// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prediccion.acciones2.domain;

import com.prediccion.acciones2.domain.CompanyHistoricDataOnDemand;
import com.prediccion.acciones2.domain.CompanyHistoricIntegrationTest;
import com.prediccion.acciones2.service.CompanyHistoricService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CompanyHistoricIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CompanyHistoricIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CompanyHistoricIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CompanyHistoricIntegrationTest: @Transactional;
    
    @Autowired
    CompanyHistoricDataOnDemand CompanyHistoricIntegrationTest.dod;
    
    @Autowired
    CompanyHistoricService CompanyHistoricIntegrationTest.companyHistoricService;
    
    @Test
    public void CompanyHistoricIntegrationTest.testCountAllCompanyHistorics() {
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", dod.getRandomCompanyHistoric());
        long count = companyHistoricService.countAllCompanyHistorics();
        Assert.assertTrue("Counter for 'CompanyHistoric' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testFindCompanyHistoric() {
        CompanyHistoric obj = dod.getRandomCompanyHistoric();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to provide an identifier", id);
        obj = companyHistoricService.findCompanyHistoric(id);
        Assert.assertNotNull("Find method for 'CompanyHistoric' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CompanyHistoric' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testFindAllCompanyHistorics() {
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", dod.getRandomCompanyHistoric());
        long count = companyHistoricService.countAllCompanyHistorics();
        Assert.assertTrue("Too expensive to perform a find all test for 'CompanyHistoric', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CompanyHistoric> result = companyHistoricService.findAllCompanyHistorics();
        Assert.assertNotNull("Find all method for 'CompanyHistoric' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CompanyHistoric' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testFindCompanyHistoricEntries() {
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", dod.getRandomCompanyHistoric());
        long count = companyHistoricService.countAllCompanyHistorics();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CompanyHistoric> result = companyHistoricService.findCompanyHistoricEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CompanyHistoric' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CompanyHistoric' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testFlush() {
        CompanyHistoric obj = dod.getRandomCompanyHistoric();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to provide an identifier", id);
        obj = companyHistoricService.findCompanyHistoric(id);
        Assert.assertNotNull("Find method for 'CompanyHistoric' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCompanyHistoric(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CompanyHistoric' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testUpdateCompanyHistoricUpdate() {
        CompanyHistoric obj = dod.getRandomCompanyHistoric();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to provide an identifier", id);
        obj = companyHistoricService.findCompanyHistoric(id);
        boolean modified =  dod.modifyCompanyHistoric(obj);
        Integer currentVersion = obj.getVersion();
        CompanyHistoric merged = companyHistoricService.updateCompanyHistoric(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CompanyHistoric' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testSaveCompanyHistoric() {
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", dod.getRandomCompanyHistoric());
        CompanyHistoric obj = dod.getNewTransientCompanyHistoric(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CompanyHistoric' identifier to be null", obj.getId());
        try {
            companyHistoricService.saveCompanyHistoric(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CompanyHistoric' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CompanyHistoricIntegrationTest.testDeleteCompanyHistoric() {
        CompanyHistoric obj = dod.getRandomCompanyHistoric();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyHistoric' failed to provide an identifier", id);
        obj = companyHistoricService.findCompanyHistoric(id);
        companyHistoricService.deleteCompanyHistoric(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'CompanyHistoric' with identifier '" + id + "'", companyHistoricService.findCompanyHistoric(id));
    }
    
}
