// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prediccion.acciones2.domain;

import com.prediccion.acciones2.domain.LogCompanyQuery;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LogCompanyQuery_Roo_Configurable {
    
    declare @type: LogCompanyQuery: @Configurable;
    
}
